# : << EOF
set -g mouse on

set-option -a terminal-features 'screen-256color:RGB'

set -g status-position top
set -g status-interval 1

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

set -g prefix C-a

set -g @plugin "catppuccin/tmux"

set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_status_justify "centre"

set -g @catppuccin_window_right_separator "█ "
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_middle_separator " | "

set -g @catppuccin_window_default_fill "none"
set -g @catppuccin_window_current_fill "all"

set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_status_right_separator "█"

set -g @catppuccin_status_modules_right "date_time"
set -g @catppuccin_status_modules_left "user host"
set -g @catppuccin_date_time_text "%d/%m %T"

set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "tmux-plugins/tmux-pain-control"

run "cut -c3- $HOME/.config/tmux/tmux.conf | bash -s"

run "$HOME/.config/tmux/plugins/tpm/tpm"

# EOF
# TPM="$HOME/.config/tmux/plugins/tpm"
# if [ ! -d $TPM ]; then
#	git clone https://github.com/tmux-plugins/tpm $TPM 
# fi
